// <auto-generated />
using System;
using EuropeanContracts.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EuropeanContracts.Infrastructure.Migrations
{
    [DbContext(typeof(EuropeanContractsDbContext))]
    [Migration("20240327110806_NameOnFirstSupplierChanged")]
    partial class NameOnFirstSupplierChanged
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.27")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("EuropeanContracts.Infrastructure.Data.Models.ActionType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Action identifier");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasComment("Action type additional description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("Name of action");

                    b.HasKey("Id");

                    b.ToTable("ActionsTypes");

                    b.HasComment("Тhe action we can do with the product");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "The amount is the purchase price of the goods and is in euros",
                            Name = "Sale"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Тhe price is for one month of use and is in euros",
                            Name = "Rent"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Тhe price is for transport the cargo to the delivery address and is in euros",
                            Name = "Transportation"
                        });
                });

            modelBuilder.Entity("EuropeanContracts.Infrastructure.Data.Models.Offer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Offer identifier");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("ActionTypeId")
                        .HasColumnType("int")
                        .HasComment("Action type identifier");

                    b.Property<string>("AddressOfDestination")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasComment("Address of destination");

                    b.Property<string>("CountryOfDestination")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("Country of destination");

                    b.Property<DateTime?>("DeliveryTime")
                        .HasColumnType("datetime2")
                        .HasComment("Time of delivery");

                    b.Property<bool>("IsDelivered")
                        .HasColumnType("bit")
                        .HasComment("Is the product is delivered");

                    b.Property<bool>("IsTemperatureControlNeeded")
                        .HasColumnType("bit")
                        .HasComment("Product temperature requirement");

                    b.Property<string>("LoadingAddress")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasComment("Loadring address");

                    b.Property<string>("LoadingCountry")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("Loading Country");

                    b.Property<string>("ProductDescription")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasComment("Product additional description");

                    b.Property<string>("ProductImageURL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasComment("Product picture URL");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("Product name");

                    b.Property<decimal>("ProductPrice")
                        .HasColumnType("decimal(18,6)")
                        .HasComment("Product price in EURO");

                    b.Property<int>("ProductQuantity")
                        .HasMaxLength(2147483647)
                        .HasColumnType("int")
                        .HasComment("Product quantity in kilograms");

                    b.Property<DateTime>("PublicationDay")
                        .HasColumnType("datetime2")
                        .HasComment("Publication day");

                    b.Property<int?>("RecipientId")
                        .HasColumnType("int")
                        .HasComment("Recipient identifier");

                    b.Property<int>("SupplierId")
                        .HasColumnType("int")
                        .HasComment("Supplier identifier");

                    b.Property<int?>("TransporterId")
                        .HasColumnType("int")
                        .HasComment("Transport company identifier");

                    b.HasKey("Id");

                    b.HasIndex("ActionTypeId");

                    b.HasIndex("RecipientId");

                    b.HasIndex("SupplierId");

                    b.HasIndex("TransporterId");

                    b.ToTable("Offers");

                    b.HasComment("Offer");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ActionTypeId = 1,
                            IsDelivered = false,
                            IsTemperatureControlNeeded = true,
                            LoadingAddress = "Badajoz, str. C.Jose.Caldito Ruiz 50",
                            LoadingCountry = "Spain",
                            ProductDescription = "The amount is the purchase price of the goods and is in euros",
                            ProductImageURL = "/Images/ProductImages/FreshPorkMeat.png",
                            ProductName = "Pork Meat",
                            ProductPrice = 102504m,
                            ProductQuantity = 19840,
                            PublicationDay = new DateTime(2024, 3, 27, 13, 8, 6, 422, DateTimeKind.Local).AddTicks(5015),
                            SupplierId = 1
                        },
                        new
                        {
                            Id = 2,
                            ActionTypeId = 3,
                            AddressOfDestination = "Burgas,Lozovo district, str.Ruzha 1",
                            CountryOfDestination = "Bulgaria",
                            IsDelivered = false,
                            IsTemperatureControlNeeded = false,
                            LoadingAddress = "Foggia, str. Via Daniele Manin 14",
                            LoadingCountry = "Italy",
                            ProductDescription = "Тhe price is for transport the cargo to the delivery address and is in euros",
                            ProductImageURL = "/Images/ProductImages/PlasticWaste.png",
                            ProductName = "Plastic waste",
                            ProductPrice = 4200m,
                            ProductQuantity = 17800,
                            PublicationDay = new DateTime(2024, 3, 27, 13, 8, 6, 422, DateTimeKind.Local).AddTicks(5017),
                            SupplierId = 2
                        },
                        new
                        {
                            Id = 3,
                            ActionTypeId = 2,
                            IsDelivered = false,
                            IsTemperatureControlNeeded = false,
                            LoadingAddress = "Vienna, str. Sindelargasse 17",
                            LoadingCountry = "Austria",
                            ProductDescription = "Тhe price is for one month of use and is in euros",
                            ProductImageURL = "/Images/ProductImages/ScaffoldingMaterials.png",
                            ProductName = "Scaffolding material",
                            ProductPrice = 3500m,
                            ProductQuantity = 19900,
                            PublicationDay = new DateTime(2024, 3, 27, 13, 8, 6, 422, DateTimeKind.Local).AddTicks(5019),
                            SupplierId = 1
                        });
                });

            modelBuilder.Entity("EuropeanContracts.Infrastructure.Data.Models.RecipientCompany", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Recipient company identifier");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasComment("Recipient company address");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("Recipient company country");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasComment("Recipient company identifier");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("Recipient company phone number");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.HasIndex("Name", "Country")
                        .IsUnique();

                    b.ToTable("RecipientsCompanies");

                    b.HasComment("Recipient company");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Charleroi, str. Rue de Marcinelle 50",
                            Country = "Belgium",
                            Name = "Global workers",
                            OwnerId = "5lk6e95e-lyj5-w25e-8w5q-9q7w8c6u3spo",
                            PhoneNumber = "+3265689899852"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Lyon, str. Rue Domer 12",
                            Country = "France",
                            Name = "LeDecale Boutique",
                            OwnerId = "dd2d2a66-rer7-y9y9-qlpq-w56a9w8s5a32",
                            PhoneNumber = "+332566985556140"
                        },
                        new
                        {
                            Id = 3,
                            Address = "Florence, str. Via Madonna Della Querce 4",
                            Country = "Italy",
                            Name = "SmartSolutions",
                            OwnerId = "d69wrpfj-asdr-uijj-j5ff-5s8q7w4e4532",
                            PhoneNumber = "+3900125221287"
                        });
                });

            modelBuilder.Entity("EuropeanContracts.Infrastructure.Data.Models.SupplierCompany", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Supplier company identifier");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("Supplier company address");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("Supplier company country");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("Supplier company identifier");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("Supplier company phone number");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.HasIndex("Name", "Country")
                        .IsUnique();

                    b.ToTable("SuppliersCompanies");

                    b.HasComment("Supplier company of product");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Thessaloniki, str. Perdika 10",
                            Country = "Greece",
                            Name = "Smart Elinas LTD",
                            OwnerId = "k3fcll56-l458-6871-q3r9-2ve3w9a54s87",
                            PhoneNumber = "+0030695422154"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Vienna, str. LowelStrasse 69",
                            Country = "Austria",
                            Name = "MDY Tools",
                            OwnerId = "k21se8s5-plow-4sw4-qzp0-128fpq6zr8klo",
                            PhoneNumber = "+4368782664400"
                        },
                        new
                        {
                            Id = 3,
                            Address = "Barcelona, str. Carrer Cruspinera 3",
                            Country = "Spain",
                            Name = "Stay Fly",
                            OwnerId = "QWE15t6s-hfgd-998q-mcs1-pekc249wlfhn",
                            PhoneNumber = "+342244501136"
                        });
                });

            modelBuilder.Entity("EuropeanContracts.Infrastructure.Data.Models.Trailer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool>("HasTemperatureControl")
                        .HasColumnType("bit")
                        .HasComment("Is there temperature control");

                    b.Property<string>("Make")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasComment("Trailer make");

                    b.Property<string>("TrailerImageURL")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("Trailer image URL");

                    b.Property<int>("TransportCompanyId")
                        .HasColumnType("int")
                        .HasComment("Owner identifier");

                    b.HasKey("Id");

                    b.HasIndex("TransportCompanyId");

                    b.ToTable("Trailers");

                    b.HasComment("Trailer");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            HasTemperatureControl = true,
                            Make = "Kodel",
                            TrailerImageURL = "/Images/TrailerImages/Kogel.png",
                            TransportCompanyId = 1
                        },
                        new
                        {
                            Id = 2,
                            HasTemperatureControl = false,
                            Make = "Krone",
                            TrailerImageURL = "/Images/TrailerImages/Krone.png",
                            TransportCompanyId = 1
                        },
                        new
                        {
                            Id = 3,
                            HasTemperatureControl = true,
                            Make = "Schmitz Cargobull",
                            TrailerImageURL = "/Images/TrailerImages/SchmitzCargobull.png",
                            TransportCompanyId = 2
                        });
                });

            modelBuilder.Entity("EuropeanContracts.Infrastructure.Data.Models.TransportCompany", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Transport company identifier");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasComment("Transport company address");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("Transport company country");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("Transport company name");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasComment("Owner identifier");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("Transport company phone number");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.HasIndex("Name", "Country")
                        .IsUnique();

                    b.ToTable("TransportsCompanies");

                    b.HasComment("Transport company of goods");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Varna, str. Popovi livadi 99",
                            Country = "Bulgaria",
                            Name = "NG TRANS",
                            OwnerId = "d33qwej9-02ap-11mnl-hflp-lpszavr2s588",
                            PhoneNumber = "+3598897415202"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Kostanza, Strada Spiru Haret 42",
                            Country = "Romania",
                            Name = "VIOREL TRANS GROUP",
                            OwnerId = "0s3a2w5e-sad5-12s5-owls-psdasfas5f5n",
                            PhoneNumber = "+00407775987456."
                        });
                });

            modelBuilder.Entity("EuropeanContracts.Infrastructure.Data.Models.Truck", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Truck identifier");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool>("HasCargoSpace")
                        .HasColumnType("bit")
                        .HasComment("Is there in truck cargo space");

                    b.Property<bool>("HasTemperatureControl")
                        .HasColumnType("bit")
                        .HasComment("Is there temperature control");

                    b.Property<int>("HorsePower")
                        .HasMaxLength(10000)
                        .HasColumnType("int")
                        .HasComment("Truck horse power");

                    b.Property<string>("Make")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasComment("Truck make");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasComment("Truck model");

                    b.Property<int>("TransportCompanyId")
                        .HasColumnType("int")
                        .HasComment("Owner identifier");

                    b.Property<string>("TruckImageURL")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("Track image URL");

                    b.HasKey("Id");

                    b.HasIndex("TransportCompanyId");

                    b.ToTable("Trucks");

                    b.HasComment("Track");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            HasCargoSpace = false,
                            HasTemperatureControl = false,
                            HorsePower = 450,
                            Make = "DAF",
                            Model = "XG+",
                            TransportCompanyId = 1,
                            TruckImageURL = "/Images/TruckImages/DAF.png"
                        },
                        new
                        {
                            Id = 2,
                            HasCargoSpace = false,
                            HasTemperatureControl = false,
                            HorsePower = 500,
                            Make = "VOLVO",
                            Model = "FX",
                            TransportCompanyId = 2,
                            TruckImageURL = "/Images/TruckImages/VOLVO.png"
                        },
                        new
                        {
                            Id = 3,
                            HasCargoSpace = true,
                            HasTemperatureControl = false,
                            HorsePower = 510,
                            Make = "SCANIA",
                            Model = "R510",
                            TransportCompanyId = 2,
                            TruckImageURL = "/Images/TruckImages/SCANIA.png"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "k3fcll56-l458-6871-q3r9-2ve3w9a54s87",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "2b29288c-ef6e-4e6b-afb7-593ea4e4d004",
                            Email = "firstUser@mail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "FIRSTUSER@MAIL.COM",
                            NormalizedUserName = "FIRSTUSER@MAIL.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEFJ3DZu0G5eTZNBzXkNJcTjDsJS8NeMkmxAXQCnzPd7z+vKS4Tfa40ArTLcW1hx1mA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "afcdeeed-51ed-4696-ae4e-4b26b5ae21e0",
                            TwoFactorEnabled = false,
                            UserName = "firstUser@mail.com"
                        },
                        new
                        {
                            Id = "k21se8s5-plow-4sw4-qzp0-128fpq6zr8klo",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "97728e8a-1f23-4782-9494-cc8c10ec9ddc",
                            Email = "secondUser@mail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "SECONDUSER@MAIL.COM",
                            NormalizedUserName = "SECONDUSER@MAIL.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEOt6mk7TlCJhDgCx/xJ54Ld/Y2ZyDxYbv4WbmXSjvpGcKFdlhshY9dMZBjpGPi/tpQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "5f224549-4e8e-480d-aea9-1971109cc956",
                            TwoFactorEnabled = false,
                            UserName = "secondUser@mail.com"
                        },
                        new
                        {
                            Id = "QWE15t6s-hfgd-998q-mcs1-pekc249wlfhn",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "ce314e74-4ec6-416f-b293-ac8e120e792b",
                            Email = "thirdUser@mail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "THIRDUSER@MAIL.COM",
                            NormalizedUserName = "THIRDUSER@MAIL.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEAA8NQE892ORYUk6y3nqOT5ZhBqr0qzTayXhx9kpWj+ThNqHaqVLpLXf0/pznTHRmg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "95f29e49-66cd-4201-a100-a3b19c774827",
                            TwoFactorEnabled = false,
                            UserName = "thirdUser@mail.com"
                        },
                        new
                        {
                            Id = "d33qwej9-02ap-11mnl-hflp-lpszavr2s588",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "4192fd53-d4ab-4c04-856e-377b2df28009",
                            Email = "fourthUser@mail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "FOURTHUSER@MAIL.COM",
                            NormalizedUserName = "FOURTHUSER@MAIL.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEMcm6G5TT6SoR52PqjlasYDLH2JurVj54XFBggwoWBxQteDrl5deAe0OrW6Q5WS8DA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "90b68ada-7563-4892-a2be-deddb6e9dca7",
                            TwoFactorEnabled = false,
                            UserName = "fourthUser@mail.com"
                        },
                        new
                        {
                            Id = "0s3a2w5e-sad5-12s5-owls-psdasfas5f5n",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "98cc59a3-89d6-4d09-b2ca-2272897d175b",
                            Email = "fifthUser@mail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "FIFTHUSER@MAIL.COM",
                            NormalizedUserName = "FIFTHUSER@MAIL.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEPZ7SJFNOWolYXV8Hm4MtwY5lDR/NGROLwkXXORGmrsUtouMYVAggory2uGzgI7g1g==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "26c46aad-363b-4832-83cf-47ad59b19bc1",
                            TwoFactorEnabled = false,
                            UserName = "fifthUser@mail.com"
                        },
                        new
                        {
                            Id = "5lk6e95e-lyj5-w25e-8w5q-9q7w8c6u3spo",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "34faee56-e9d3-4f35-b4ae-fcad98ca7e1b",
                            Email = "sixthUser@mail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "SIXTHUSER@MAIL.COM",
                            NormalizedUserName = "SIXTHUSER@MAIL.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEChvtj269vU93e6UKqM5+l/mU6hP4lhNns8z2VYSxsQpP7P0obWFqNTvOwZIIY5lWQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "8e167fb9-eed0-4d98-ad83-893a8208d769",
                            TwoFactorEnabled = false,
                            UserName = "sixthUser@mail.com"
                        },
                        new
                        {
                            Id = "dd2d2a66-rer7-y9y9-qlpq-w56a9w8s5a32",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "8496502f-96d7-49fb-8e09-cb9e07e5180c",
                            Email = "seventhuser@mail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "SEVENTHUSER@MAIL.COM",
                            NormalizedUserName = "SEVENTHUSER@MAIL.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEEa2eMnZYAoT2ta+G1/gUUijcm5r46Bxv7ZqZuBTn7OcjVfnZHmu5QCkOonCW1dEEg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "e7fab72e-9e32-4014-b807-80dea66b4bba",
                            TwoFactorEnabled = false,
                            UserName = "seventhUser@mail.com"
                        },
                        new
                        {
                            Id = "d69wrpfj-asdr-uijj-j5ff-5s8q7w4e4532",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "bd9856ab-c940-4ce2-88cc-ae1129769781",
                            Email = "eighthUser@mail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "EIGHTHUSER@MAIL.COM",
                            NormalizedUserName = "EIGHTHUSER@MAIL.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEABp4dV3qmgLY3uyzK6AFZhnGwL+1OZ/Aq7qRYLdP2DhP9q+iFlILM0P0KXU2feCZQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "6a0581e6-3f0c-40c4-bb7a-40e7f4d4c23a",
                            TwoFactorEnabled = false,
                            UserName = "eighthUser@mail.com"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("EuropeanContracts.Infrastructure.Data.Models.Offer", b =>
                {
                    b.HasOne("EuropeanContracts.Infrastructure.Data.Models.ActionType", "ActionType")
                        .WithMany("Offer")
                        .HasForeignKey("ActionTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EuropeanContracts.Infrastructure.Data.Models.RecipientCompany", "Recipient")
                        .WithMany("Offers")
                        .HasForeignKey("RecipientId");

                    b.HasOne("EuropeanContracts.Infrastructure.Data.Models.SupplierCompany", "Supplier")
                        .WithMany("Offers")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EuropeanContracts.Infrastructure.Data.Models.TransportCompany", "Transporter")
                        .WithMany("Offers")
                        .HasForeignKey("TransporterId");

                    b.Navigation("ActionType");

                    b.Navigation("Recipient");

                    b.Navigation("Supplier");

                    b.Navigation("Transporter");
                });

            modelBuilder.Entity("EuropeanContracts.Infrastructure.Data.Models.RecipientCompany", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("EuropeanContracts.Infrastructure.Data.Models.SupplierCompany", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("EuropeanContracts.Infrastructure.Data.Models.Trailer", b =>
                {
                    b.HasOne("EuropeanContracts.Infrastructure.Data.Models.TransportCompany", "TransportCompany")
                        .WithMany("Trailers")
                        .HasForeignKey("TransportCompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TransportCompany");
                });

            modelBuilder.Entity("EuropeanContracts.Infrastructure.Data.Models.TransportCompany", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("EuropeanContracts.Infrastructure.Data.Models.Truck", b =>
                {
                    b.HasOne("EuropeanContracts.Infrastructure.Data.Models.TransportCompany", "TransportCompany")
                        .WithMany("Trucks")
                        .HasForeignKey("TransportCompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TransportCompany");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EuropeanContracts.Infrastructure.Data.Models.ActionType", b =>
                {
                    b.Navigation("Offer");
                });

            modelBuilder.Entity("EuropeanContracts.Infrastructure.Data.Models.RecipientCompany", b =>
                {
                    b.Navigation("Offers");
                });

            modelBuilder.Entity("EuropeanContracts.Infrastructure.Data.Models.SupplierCompany", b =>
                {
                    b.Navigation("Offers");
                });

            modelBuilder.Entity("EuropeanContracts.Infrastructure.Data.Models.TransportCompany", b =>
                {
                    b.Navigation("Offers");

                    b.Navigation("Trailers");

                    b.Navigation("Trucks");
                });
#pragma warning restore 612, 618
        }
    }
}
